#!/usr/bin/env bash

##################################################
# $ # To migrate up a fresh machine              #
#                                                #
# $ curl -Lks <url to this script> | /bin/bash   #
##################################################

# to use my default settings:
# sudo curl -Lks https://github.io/ei9h7/automated-machine-install/bootstrap-linux.sh | bin/bash

# ensure Python3 is in path
export PATH="/usr/bin/python3:$PATH"

# update and upgrade apt and install dependencies
sudo apt-get update && apt-get dist-upgrade -y
sudo apt-get install -y git

# upgrade pip and install ansible
sudo pip3 install --upgrade pip
pip3 install --ignore-installed ansible

# clone project repo to local machine
[ -d "$HOME/projects" ] || mkdir -p $HOME/projects
cd $HOME/projects
git clone https://github.com/ei9h7/automated-machine-setup.git
git clone https://github.com/ei9h7/dotfiles.git
cd automated-machine-setup

# backup existing dotfiles before running machine setup
mkdir -p .dotfiles-backup 
git --git-dir="$HOME/projects/dotfiles/" --work-tree="$HOME" checkout
[ $? = 0 ] || echo "Backing up pre-existing dot files." && git --git-dir="$HOME/projects/dotfiles/" --work-tree="$HOME" checkout 2>&1 | egrep "\s+\." | awk {'print $1'} | xargs -I{} cp {} "$HOME/projects/automated-machine-setup/.dotfiles-backup/{}"

# ansible install requirements 
ansible-galaxy install -r requirements.yml

# encrypt your own secrets.yml file
# ansible-vault encrypt secrets.yml

# encrypt local .gitconfig file
cp "$HOME/.gitconfig" "$HOME/projects/dotfiles/.config/git/config.enc" && ansible-vault encrypt "$HOME/projects/dotfiles/.config/git/config.enc"

ansible-playbook main.yml --ask-vault-pass --ask-become-password 
