#!/bin/sh
xcode-select --install
sudo xcodebuild -license
/usr/sbin/softwareupdate --install-rosetta
curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
python3 get-pip.py
sudo pip3 install ansible
ansible-galaxy install -r requirements.yml
chmod +x update
sh update
