#!/bin/sh

# Install Command Line Tools
echo "Checking Xcode CLI tools"
# Only run if the tools are not installed yet
# To check that try to print the SDK path
xcode-select -p &> /dev/null
if [ $? -ne 0 ]; then
  echo "Xcode CLI tools not found. Installing them..."
  touch /tmp/.com.apple.dt.CommandLineTools.installondemand.in-progress;
  PROD=$(softwareupdate -l |
    grep "\*.*Command Line" |
    tail -n 1 | sed 's/^[^C]* //')
  softwareupdate -i "$PROD" --verbose;
else
  echo "Xcode CLI tools OK"
fi

#install homebrew
echo "Checking Homebrew Install"
# Install Homebrew if it is not installed
if [[ $(command -v brew) == "" ]]; then 
  echo "Installing Homebrew.. "
  ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
else
  echo "Updating Homebrew.. "
  brew update
fi

#install python3/pip
echo "Checking Python3/pip Install"
# Install if Python3/pip is not installed yet
command -v pip3 &> /dev/null
if [ $? -ne 0 ]; then
    echo 'pip3 not found. Installing pip...'
    brew install python3
else
     echo 'python3/pip already installed.' 
fi

#install ansible
echo "Checking for Ansible Install"
# If not installed then install with pip
pip3 show ansible &> /dev/null
if [ $? -ne 0 ]; then
    echo 'Ansible not found. Installing Ansible...'
    sudo pip3 install ansible --ignore-installed
else
     echo 'Ansible already installed.' 
fi

#install machine setup ansible requirements
echo 'Install Ansible Galaxy Requirements'
ansible-galaxy install -r requirements.yml

# run machine setup/update ansible playbook
chmod +x update
sh update
