#!/bin/sh

# ensure Python3 is in path
export PATH="/usr/bin/Python3"

# update and upgrade apt and install dependencies
sudo apt-get update && apt-get dist-upgrade -y
sudo apt-get install -y git

# upgrade pip and install ansible
sudo pip3 install --upgrade pip
pip3 install --ignore-installed ansible

# clone project repo to local machine
mkdir -p $HOME/projects && cd $HOME/projects
git clone https://github.com/ei9h7/automated-machine-setup.git
cd automated-machine-setup

# ansible install requirements 
ansible-galaxy install -r requirements.yml

# encrypt your own secrets.yml file
   # ansible-vault encrypt secrets.yml

# encrypt local .gitconfig file
cp $HOME/.gitconfig $HOME/projects/dotfiles/.config/git/config.enc && ansible-vault encrypt $HOME/projects/dotfiles/.config/git/config.enc

ansible-playbook main.yml --ask-vault-pass --ask-become-password 
