---
downloads: "{{ lookup('env', 'HOME') }}/.ansible-downloads/"

configure_dotfiles: true
dotfiles_repo: https://github.com/ei9h7/dotfiles.git
dotfiles_repo_version: master
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: "{{ lookup('env', 'HOME') }}/projects/dotfiles"
dotfiles_home: "{{ lookup('env', 'HOME') }}"
dotfiles_files:
  - .config/htop
  - .config/neofetch
  - .config/git/config
  - .gnupg/gpg-agent.conf
  - .iterm2
  - .bash_profile
  - .bashrc
  - .gitignore
  - .gitmodules
  - .hyper.js
  - .inputrc
  - .mackup.cfg
  - .nanorc
  - .profile
  - .screenrc
  - .tmux.conf
  - .vimrc
  - .zshrc
  - .zshenv

configure_sudoers: true
sudoers_custom_config: '%admin ALL=(ALL) NOPASSWD: ALL'
# Example:
# sudoers_custom_config: |
#   # Allow users in admin group to use sudo with no password.
#   %admin ALL=(ALL) NOPASSWD: ALL

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
gem_packages:
  - name: colorls
    state: latest
npm_packages: []
pip_packages: []

# configure yubikey
configure_yubikey: true

# Set to 'true' to configure Visual Studio Code
configure_vsc: false
vsc_extensions:
  - azblockchain.azure-blockchain
  - coenraads.bracket-pair-colorizer-2
  - aaronyoung.dark-synthwave-vscode
  - ms-azuretools.vscode-docker
  - formulahendry.docker-explorer
  - quentingruber.dockerfiletemplate
  - tqrhsn.vscode-docker-registry-explorer
  - george3447.docker-run
  - dotiful.dotfiles-syntax-highlighting
  - blake-mealey.generate-wt-scheme
  - mhutchie.git-graph
  - github.codespaces
  - github.vscode-pull-request-github
  - ntc.integrated-terminal-tasks
  - hoovercj.vscode-power-mode
  - stuyk.powermodesounds
  - ms-python.python
  - dhedgecock.radical-vscode
  - ms-vscode-remote.remote-containers
  - ms-vscode-remote.remote-ssh
  - ms-vscode-remote.remote-ssh-edit
  - ms-vscode-remote.remote-wsl
  - ms-vscode-remote.vscode-remote-extensionpack
  - juanblanco.solidity
  - robbowen.synthwave-vscode
  - visualstudioexptteam.vscodeintellicode
  - dunstontc.vscode-docker-syntax
  - redhat.vscode-yaml
  - ms-vscode.powershell
vsc_settings_overwrite: no
vsc_keys_overwrite: no
vsc_custom_config: $DOTFILES/.config/vscode/settings.json
vsc_custom_keys: $DOTFILES/.config/vscode/keybindings.json

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
