---
downloads: /Users/ei9h7/.ansible-downloads/

configure_dotfiles: true
configure_terminal: true
configure_osx: true

# Set to 'true' to configure the Dock via dockutil.
configure_dock: true
dockitems_remove:
  - Launchpad
  - 'App Store'
  - Mail
  - Contacts
  - Calendar
  - Maps
  - Photos
  - Messages
  - Facetime
  - News
  - iTunes
  - 'System Preferences'
dockitems_persist:
  - name: "AppCleaner"
    path: "/Applications/AppCleaner.app/"
    pos: 1
  - name: "Atom"
    path: "/Applications/Atom.app/"
    pos: 2
  - name: "Calculator"
    path: "/Applications/Calculator.app/"
    pos: 3
  - name: "Canary Mail"
    path: "/Applications/Canary Mail.app/"
    pos: 4
  - name: "Chromium"
    path: "/Applications/Chromium.app/"
    pos: 5
  - name: "Command Pad"
    path: "/Applications/Command Pad.app/"
    pos: 6
  - name: "Friendly Streaming"
    path: "/Applications/Friendly Streaming.app/"
    pos: 7
  - name: "GitKraken"
    path: "/Applications/GitKraken.app/"
    pos: 8
  - name: "MacVim"
    path: "/Applications/MacVim.app/"
    pos: 9
  - name: "Marko"
    path: "/Applications/Marko.app/"
    pos: 10
  - name: "Meld"
    path: "/Applications/Meld.app/"
    pos: 11
  - name: "NVIDIA GeForce NOW"
    path: "/Applications/NVIDIA GeForce NOW.app/"
    pos: 12
  - name: "PhpStorm"
    path: "/Applications/PhpStorm.app/"
    pos: 13
  - name: "PyCharm Edu"
    path: "/Applications/PyCharm Edu.app/"
    pos: 14
  - name: "Stickies"
    path: "/Applications/Stickies.app/"
    pos: 15
  - name: "Therm"
    path: "/Applications/Therm.app/"
    pos: 16
  - name: "Visual Studio Code"
    path: "/Applications/Visual Studio Code.app/"
    pos: 17
  - name: "NVIDIA GeForce NOW"
    path: "/Applications/NVIDIA GeForce NOW.app/"
    pos: 18

configure_sudoers: false
sudoers_custom_config: ''
# Example:
# sudoers_custom_config: |
#   # Allow users in admin group to use sudo with no password.
#   %admin ALL=(ALL) NOPASSWD: ALL

dotfiles_repo: https://github.com/ei9h7/dotfiles.git
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: /Users/ei9h7/projects/dotfiles
dotfiles_files:
  - .atom/*
  - .config/*
  - .cups/*
  - .gnupg/*
  - .iterm2/*
  - .tmux/*
  - .bash_profile
  - .bashrc
  - .gitignore
  - .gitmodules
  - .hyper.js
  - .inputrc
  - .mackup.cfg
  - .nanorc
  - .profile
  - .screenrc
  - .tmux.conf
  - .vimrc
  - .zshrc

homebrew_installed_packages:
# - ansible # Installed via Pip.
  - autoconf
  - automake
  - bash
  - bash-completion
  - bash-git-prompt
  - bash-snippets
  - ca-certificates
  - ccat
# - docker
# - docker-completion
# - docker-compose
# - docker-compose-completion
# - docker-machine
# - docker-machine-parallels
# - docker-toolbox
  - e2fsprogs
  - ethereum
  - fortune
  - gh
  - git
  - go
  - hub
  - lazydocker
  - libtool
  - python@3.9
  - imagemagick
  - libmusicbrainz
  - libyubikey
  - luarocks
  - m4
  - micro
  - node
  - nyancat
  - openjdk
  - p7zip
  - pam_yubico
  - perl@5.18
  - rclone
  - rsync
  - rsync-time-backup
  - screen
  - shpotify
  - storj-uplink
  - thefuck
  - tldr
  - tmux
  - tmux-xpanes
  - wimlib
  - x11vnc
  - ykpers
  - yubico-piv-tool
  - yubikey-agent
  - zsh
  - zsh-git-prompt
  - zsh-lovers

homebrew_taps:
  - homebrew/bundle
  - homebrew/cask
  - homebrew/cask-drivers
  - homebrew/cask-fonts
  - homebrew/cask-versions
  - homebrew/command-not-found
  - homebrew/core
  - homebrew/services
  - mas-cli/tap
  - nrlquaker/createzap

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - 1clipboard
  - amazon-music
  - angry-ip-scanner
  - appcleaner
  - atom
  - balenaetcher
  - backuploupe
  - battle-net
  - boxcryptor
  - carbon-copy-cloner5
  - command-pad
  - docker
  - duplicati
  - eloston-chromium
  - font-fira-code-nerd-font
  - font-fira-mono-nerd-font
  - font-hack-nerd-font
  - font-jetbrains-mono-nerd-font
  - font-meslo-lg-nerd-font
  - font-victor-mono-nerd-font
  - gitkraken
  - google-chrome
  - google-drive-file-stream
  - gpg-suite-no-mail
  - icanhazshortcut
  - jetbrains-toolbox
  - keka
  - kekaexternalhelper
  - keybase
  - lens
  - macfuse
  - macs-fan-control
  - macvim
  - mdrp
  - microsoft-auto-update
  - microsoft-office
  - multipass
  - musicbrainz-picard
  - nordlocker
  - nordpass
  - nordvpn
  - nvidia-geforce-now
  - obs
  - obs-ndi
  - obs-virtualcam
  - obs-websocket
  - parallels12
  - phpstorm
  - plex
  - plexamp
  - pycharm-edu
  - raspberry-pi-imager
  - spotify
  - spotify-now-playing
  - steam
  - therm
  - the-unarchiver
  - tunnelblick
  - unetbootin
  - unity
  - unity-hub
  - vagrant
  - virtualbox
  - visual-studio
  - visual-studio-code
  - vlc
  - vnc-viewer
  - wireshark
  - yubico-authenticator
  - yubico-yubikey-manager
  - yubico-yubikey-personalization-gui
  - yubico-yubikey-piv-manager

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps:
  - { id: 937984704, name: "Amphetamine" }
  - { id: 1236045954, name: "Canary Mail" }
  - { id: 696977615, name: "Capo" }
  - { id: 484889220, name: "Cryptext" }
  - { id: 1012138285, name: "Crypto-Maker" }
  - { id: 425264550, name: "Disk Speed Test" }
  - { id: 1406832001, name: "Emporter" }
  - { id: 935235287, name: "Encrypto" }
  - { id: 1298486723, name: "Filezilla" }
  - { id: 909212772, name: "Fhotoroom X" }
  - { id: 486626129, name: "Folder Tidy" }
  - { id: 553245401, name: "Friendly Streaming" }
  - { id: 1090488118, name: "Gemini 2" }
  - { id: 490152466, name: "iBooks Author" }
  - { id: 607997198, name: "Marko" }
  - { id: 533491939, name: "Mint QuickView" }
  - { id: 409203825, name: "Numbers" }
  - { id: 1520395378, name: "Ownr Crypto Wallet" }
  - { id: 409201541, name: "Pages" }
  - { id: 888806818, name: "Password Factory" }
  - { id: 1099475282, name: "SnailGit Lite" }
  - { id: 707452888, name: "Spike Email" }
  - { id: 1452212620, name: "StartUp" }
  - { id: 1496833156, name: "Swift Playgrounds" }
  - { id: 1102494854, name: "System Designer" }
  - { id: 571654652, name: "Toolbox for Pages" }
  - { id: 1480933944, name: "Vimari" }
  - { id: 497799835, name: "Xcode" }
  - { id: 1237435595, name: "XCRegex" }
  - { id: 1438287690, name: "ZipMounter Lite" }
# mas_email: ""
# mas_password: "" # in config.yml which is gitignored

osx_script: "/Users/ei9h7/projects/dotfiles/.macos-defaults --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
# - name: drush
#   state: present # present/absent, default: present
#   version: "^8.1" # default: N/A
gem_packages: []
# - name: bundler
#   state: present # present/absent/latest, default: present
#   version: "~> 1.15.1" # default: N/A
npm_packages: []
# - name: webpack
#   state: present # present/absent/latest, default: present
#   version: "^2.6" # default: N/A
pip_packages: []
# - name: mkdocs
#   state: present # present/absent/latest, default: present
#   version: "0.16.3" # default: N/A

# Set to 'true' to configure Sublime Text.
configure_sublime: false
sublime_base_path: '~/Library/Application Support/Sublime Text'
sublime_config_path: "Packages/User"
sublime_package_control:
  - "Dockerfile Syntax Highlighting"
  - "FileDiffs"
  - "GitHub Flavored Markdown Preview"
  - "Package Control"
  - "Pretty JSON"
  - "TrailingSpaces"

# Set to 'true' to configure Visual Studio Code
configure_vsc: true
vsc_user: ei9h7
vsc_extensions:
  - azblockchain.azure-blockchain
  - coenraads.bracket-pair-colorizer-2
  - aaronyoung.dark-synthwave-vscode
  - ms-azuretools.vscode-docker
  - formulahendry.docker-explorer
  - quentingruber.dockerfiletemplate
  - tqrhsn.vscode-docker-registry-explorer
  - george3447.docker-run
  - dotiful.dotfiles-syntax-highlighting
  - blake-mealey.generate-wt-scheme
  - mhutchie.git-graph
  - github.codespaces
  - github.vscode-pull-request-github
  - ntc.integrated-terminal-tasks
  - hoovercj.vscode-power-mode
  - stuyk.powermodesounds
  - ms-python.python
  - dhedgecock.radical-vscode
  - ms-vscode-remote.remote-containers
  - ms-vscode-remote.remote-ssh
  - ms-vscode-remote.remote-ssh-edit
  - ms-vscode-remote.remote-wsl
  - ms-vscode-remote.vscode-remote-extensionpack
  - juanblanco.solidity
  - robbowen.synthwave-vscode
  - visualstudioexptteam.vscodeintellicode
  - dunstontc.vscode-docker-syntax
  - redhat.vscode-yaml
  - ms-vscode.powershell
vsc_settings_overwrite: yes
vsc_custom_config: |
  {
  // THEME
      "workbench.colorTheme": "SynthWave '84",
      "synthwave84.brightness": 1,
      "darkSynthwave84.brightness": 1,
      "powermode.enabled": true,

  // EDITOR SETTINGS
      "editor.suggestSelection": "first",
      "vsintellicode.modify.editor.suggestSelection": "automaticallyOverrodeDefaultValue",
      "atomKeymap.promptV3Features": true,
      "editor.multiCursorModifier": "ctrlCmd",
      "editor.formatOnPaste": true,
      "workbench.startupEditor": "newUntitledFile",
      "editor.fontFamily": "VictorMono Nerd Font",
      "editor.fontLigatures": true,
      "editor.fontSize": 17,
      "editor.letterSpacing": 1,
      "workbench.editorAssociations": {
          "*.ipynb": "jupyter.notebook.ipynb"
      },

  // TERMINAL SETTINGS
      "terminal.integrated.fontFamily": "VictorMono Nerd Font",
      "terminal.integrated.copyOnSelection": true,
      "terminal.integrated.fontSize": 15,
      "terminal.integrated.letterSpacing": 1,
      "terminal.integrated.tabs.enabled": true,

      // macOS
      "terminal.external.osxExec": "Therm.app",
      "terminal.integrated.env.osx": {},
      "terminal.integrated.macOptionIsMeta": true,
      "terminal.integrated.profiles.osx": {
          "bash": {
              "path": "bash"
          },
          "zsh": {
              "path": "zsh",
              "args": ["-l"]
          },
          "pwsh": {
              "path": "pwsh"
          }
      },
      "terminal.integrated.defaultProfile.osx": "bash",

      // WINDOWS
      "terminal.integrated.profiles.windows": {
          "PowerShell 7": {
              "path": "C:\\Program Files\\PowerShell\\7\\pwsh.exe",
          },
          "Command Prompt": {
              "path": "C:\\Windows\\System32\\cmd.exe",
          },
          "Debian (WSL)": {
              "path": "C:\\Windows\\System32\\wsl.exe -d Debian",
          },
          "Kali (WSL)": {
              "path": "C:\\Windows\\System32\\wsl.exe -d Kali",
          }
      },
      "terminal.integrated.defaultProfile.windows": "Debian (WSL)",
      "terminal.external.windowsExec": "C:\\Program Files\\WindowsApps\\Microsoft.WindowsTerminal_1.8.1444.0_x64__8wekyb3d8bbwe\\WindowsTerminal.exe",

      // LINUX
      "terminal.integrated.profiles.linux": {
          "bash": {
              "path": "bash"
          },
          "zsh": {
              "path": "zsh"
          },
          "screen": {
              "path": "screen"
          },
          "pwsh": {
              "path": "pwsh",
              "icon": "terminal-powershell"
          }
      },
      "terminal.integrated.defaultProfile.linux": "screen",

  // EXTENSION SETTINGS
      "bracket-pair-colorizer-2.colors": [
          "#DFF959",
          "#F834BB",
          "#2BF5E9",
          "#D831D7"
      ],
      "git-graph.graph.colours": [
          "#FF428E",
          "#A8FFEF",
          "#DFF959",
          "#F7A409",
          "#F834BB",
          "#2BF5E9",
          "#D831D7",
          "#FF594C"
      ],
      "DockerRun.DisableAutoGenerateConfig": true,
      "workbench.sideBar.location": "right",
      "git.enableCommitSigning": true,
      "redhat.telemetry.enabled": true,
      "telemetry.telemetryLevel": "off"
  }

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
