---
configure_osx: true
osx_script: "{{ lookup('env', 'DOTFILES') }}/.macos-defaults --no-restart"
# Set default shell (choose only one)
set_zsh: false
set_bash: true

configure_homebrew: true
homebrew_repo: https://github.com/Homebrew/brew
homebrew_prefix: "{{ (ansible_machine == 'arm64') | ternary('/opt/homebrew', '/usr/local') }}"
homebrew_install_path: "{{ homebrew_prefix }}/Homebrew"
homebrew_brew_bin_path: "{{ homebrew_prefix }}/bin"
homebrew_upgrade_all_packages: false
homebrew_cask_accept_external_apps: false
homebrew_use_brewfile: false
homebrew_brewfile_dir: "$DOTFILES"
homebrew_clear_cache: false
homebrew_folders_additional: []
homebrew_installed_packages:
# - ansible # Installed via Pip.
  - autoconf
  - automake
  - bash
  - bash-completion
  - bash-git-prompt
  - bash-snippets
  - ca-certificates
  - ccat
# - docker
# - docker-completion
# - docker-compose
# - docker-compose-completion
# - docker-machine
# - docker-machine-parallels
# - docker-toolbox
  - e2fsprogs
  - ethereum
  - fortune
  - gcc
  - gh
  - git
  - go
  - grc
  - hub
  - lazydocker
  - libtool
  - python@3.9
  - imagemagick
  - libmusicbrainz
  - libyubikey
  - luarocks
  - m4
  - micro
  - node
  - nyancat
  - openjdk
  - p7zip
  - pam_yubico
  - perl@5.18
  - pinentry-mac
  - rclone
  - rsync
  - rsync-time-backup
  - screen
  - shpotify
  - storj-uplink
  - thefuck
  - tldr
  - tmux
  - tmux-xpanes
  - wimlib
  - x11vnc
  - ykpers
  - yubico-piv-tool
  - { name: yubikey-agent, install_options: "restart_service: true" }
  - zsh
  - zsh-git-prompt
  - zsh-lovers
homebrew_uninstalled_packages: []
homebrew_taps:
  - homebrew/bundle
  - homebrew/cask
  - homebrew/cask-drivers
  - homebrew/cask-fonts
  - homebrew/cask-versions
  - homebrew/command-not-found
  - homebrew/core
  - homebrew/services
  - mas-cli/tap
  - nrlquaker/createzap
homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - 1clipboard
  - amazon-music
  - angry-ip-scanner
  - appcleaner
  - atom
  - balenaetcher
  - backuploupe
  - battle-net
  - boxcryptor
  - carbon-copy-cloner5
  - command-pad
  - docker
  - duplicati
  - eloston-chromium
  - font-fira-code-nerd-font
  - font-fira-mono-nerd-font
  - font-hack-nerd-font
  - font-jetbrains-mono-nerd-font
  - font-meslo-lg-nerd-font
  - font-victor-mono-nerd-font
  - gitkraken
  - google-chrome
  - google-drive-file-stream
  - gpg-suite-no-mail
  - icanhazshortcut
  - jetbrains-toolbox
  - keka
  - kekaexternalhelper
  - keybase
  - lens
  - macfuse
  - macs-fan-control
  - macvim
  - mdrp
  - microsoft-auto-update
  - microsoft-office
  - multipass
  - musicbrainz-picard
  - nordlocker
  - nordpass
  - nordvpn
  - nvidia-geforce-now
  - obs
  - obs-ndi
  - obs-virtualcam
  - obs-websocket
  - parallels12
  - phpstorm
  - plex
  - plexamp
  - pycharm-edu
  - raspberry-pi-imager
  - spotify
  - spotify-now-playing
  - steam
  - therm
  - the-unarchiver
  - tunnelblick
  - unetbootin
  - unity
  - unity-hub
  - vagrant
  - virtualbox
  - visual-studio
  - visual-studio-code
  - vlc
  - vnc-viewer
  - wireshark
  - yubico-authenticator
  - yubico-yubikey-manager
  - yubico-yubikey-personalization-gui
  - yubico-yubikey-piv-manager
homebrew_cask_uninstalled_apps: []

# Set to 'true' to configure the terminal theme etc
configure_terminal: true

# Set to 'true' to configure the Dock via dockutil.
configure_dock: true
dockitems_remove:
  - Launchpad
  - 'App Store'
  - Mail
  - Contacts
  - Calendar
  - Maps
  - Photos
  - Messages
  - Facetime
  - News
  - iTunes
  - 'System Preferences'
dockitems_persist:
  - name: "AppCleaner"
    path: "/Applications/AppCleaner.app/"
    pos: 1
  - name: "Atom"
    path: "/Applications/Atom.app/"
    pos: 2
  - name: "Calculator"
    path: "/Applications/Calculator.app/"
    pos: 3
  - name: "Canary Mail"
    path: "/Applications/Canary Mail.app/"
    pos: 4
  - name: "Chromium"
    path: "/Applications/Chromium.app/"
    pos: 5
  - name: "Command Pad"
    path: "/Applications/Command Pad.app/"
    pos: 6
  - name: "Friendly Streaming"
    path: "/Applications/Friendly Streaming.app/"
    pos: 7
  - name: "GitKraken"
    path: "/Applications/GitKraken.app/"
    pos: 8
  - name: "MacVim"
    path: "/Applications/MacVim.app/"
    pos: 9
  - name: "Marko"
    path: "/Applications/Marko.app/"
    pos: 10
  - name: "Meld"
    path: "/Applications/Meld.app/"
    pos: 11
  - name: "NVIDIA GeForce NOW"
    path: "/Applications/NVIDIA GeForce NOW.app/"
    pos: 12
  - name: "PhpStorm"
    path: "/Applications/PhpStorm.app/"
    pos: 13
  - name: "PyCharm Edu"
    path: "/Applications/PyCharm Edu.app/"
    pos: 14
  - name: "Stickies"
    path: "/Applications/Stickies.app/"
    pos: 15
  - name: "Therm"
    path: "/Applications/Therm.app/"
    pos: 16
  - name: "Visual Studio Code"
    path: "/Applications/Visual Studio Code.app/"
    pos: 17
  - name: "NVIDIA GeForce NOW"
    path: "/Applications/NVIDIA GeForce NOW.app/"
    pos: 18

configure_macstore: true
mas_installed_app_ids: []  # Deprecated
mas_installed_apps:
  - { id: 937984704, name: "Amphetamine" }
  - { id: 1236045954, name: "Canary Mail" }
#  - { id: 696977615, name: "Capo" }
  - { id: 484889220, name: "Cryptext" }
  - { id: 1012138285, name: "Crypto-Maker" }
  - { id: 425264550, name: "Disk Speed Test" }
  - { id: 1406832001, name: "Emporter" }
  - { id: 935235287, name: "Encrypto" }
  - { id: 1298486723, name: "Filezilla" }
  - { id: 909212772, name: "Fhotoroom X" }
  - { id: 486626129, name: "Folder Tidy" }
  - { id: 553245401, name: "Friendly Streaming" }
  - { id: 1090488118, name: "Gemini 2" }
  - { id: 490152466, name: "iBooks Author" }
  - { id: 607997198, name: "Marko" }
  - { id: 533491939, name: "Mint QuickView" }
  - { id: 409203825, name: "Numbers" }
  - { id: 1520395378, name: "Ownr Crypto Wallet" }
  - { id: 409201541, name: "Pages" }
  - { id: 888806818, name: "Password Factory" }
  - { id: 1099475282, name: "SnailGit Lite" }
  - { id: 707452888, name: "Spike Email" }
  - { id: 1452212620, name: "StartUp" }
# - { id: 1496833156, name: "Swift Playgrounds" }
  - { id: 1102494854, name: "System Designer" }
  - { id: 571654652, name: "Toolbox for Pages" }
  - { id: 1480933944, name: "Vimari" }
# - { id: 497799835, name: "Xcode" }
  - { id: 1237435595, name: "XCRegex" }
  - { id: 1438287690, name: "ZipMounter Lite" }
# mas_email: ""
# mas_password: "" # in config.yml which is gitignored
mas_upgrade_all_apps: false
mas_signin_dialog: false
