---

# set to true to configure linux (NOT FINISHED, need too create .linux-defaults script)
configure_linux: false
linux_script: "{{ lookup('env', 'DOTFILES') }}/.linux-defaults --no-restart"
# Set default shell (choose only one)
set_zsh: true
set_bash: false

# set to true to configure apt packages
configure_apt: true
apt_installed_packages:
  - ansible
  - vagrant
  - ruby
apt_removed_packages: []
# set yes to autoclean and autoremove 
apt_autoclean: true
apt_autoremove: true

