---
- hosts: all

  vars_files:
    - laptop.config.yml #Include linux configuration
    - vars/all.yml

  pre_tasks:
    - name: Include playbook secrets configuration.
      include_vars: secrets.yml  
    
  tasks:
    - import_tasks: tasks/dotfiles.yml
      when: configure_dotfiles
      tags: ['dotfiles']

    - import_tasks: tasks/sudoers.yml
      when: configure_sudoers
      tags: ['sudoers']

    - import_tasks: tasks/linux.yml
      when: configure_linux
      tags: ['linux']

    - import_tasks: tasks/homebrew.yml
      when: configure_homebrew
      tags: ['homebrew']

    - impor_tasks: tasks/apt.yml
      when: configure_apt
      tags: ['apt']

    - import_tasks: tasks/terminal.yml
      when: configure_terminal
      tags: ['terminal']

    - import_tasks: tasks/extra-packages.yml
      tags: ['extra-packages']
    
    - import_tasks: tasks/yubikey.yml
      when: configure_yubikey
      tags: ['yubikey']

    - import_tasks: tasks/vscode.yml
      when: configure_vsc
      tags: ['visual-studio-code']

    - name: Run configured post-provision ansible task files.
      include_tasks: "{{ outer_item }}"
      loop_control:
        loop_var: outer_item
      with_fileglob: "{{ post_provision_tasks|default(omit) }}"
      tags: ['post']
