---
- hosts: all

  vars_files:
    - default.config.yml
    - machines.yml

  pre_tasks:
    - name: Include playbook secrets configuration.
      include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
      tags: ['mas']
  
    - name: Include laptop configuration
      include_vars: laptop.config.yml
      when: setup_laptop

    - name: Include imac configuration
      include_vars: imac.config.yml
      when: setup_imac21

    - name: Include homebrew vars
      include_vars: vars/homebrew.yml
      when: configure_homebrew
      tags: ['homebrew']

  tasks:
    - import_tasks: tasks/dotfiles.yml
      when: configure_dotfiles
      tags: ['dotfiles']

    - import_tasks: tasks/homebrew.yml
      when: configure_homebrew
      tags: ['homebrew']

    - import_tasks: tasks/mas.yml
      when: configure_macstore
      tags: ['mas','user']

    - import_tasks: tasks/sudoers.yml
      when: configure_sudoers
      tags: ['sudoers']

    - import_tasks: tasks/osx.yml
      when: configure_osx
      tags: ['osx']

    - import_tasks: tasks/linux.yml
      when: configure_osx
      tags: ['linux']

    - import_tasks: tasks/dock.yml
      when: configure_dock
      tags: ['dock']

    - import_tasks: tasks/terminal.yml
      when: configure_terminal
      tags: ['terminal']

    - import_tasks: tasks/extra-packages.yml
      tags: ['extra-packages']
    
    - import_tasks: tasks/apt.yml
      when: configure_apt
      tags: ['apt-packages']

    - import_tasks: tasks/yubikey.yml
      when: configure_yubikey
      tags: ['yubikey']

    - import_tasks: tasks/vscode.yml
      when: configure_vsc
      tags: ['visual-studio-code']

    - name: Run configured post-provision ansible task files.
      include_tasks: "{{ outer_item }}"
      loop_control:
        loop_var: outer_item
      with_fileglob: "{{ post_provision_tasks|default(omit) }}"
      tags: ['post']
