---
- hosts: all

  vars_files:
    - macbookpro.yml # Include macbookpro9,1 configuration
    - vars/all.yml

  pre_tasks:
#   - name: Include playbook secrets configuration.
#     include_vars: secrets.yml     
    
  tasks:
    - import_tasks: tasks/dotfiles.yml
      when: configure_dotfiles
      tags: ['dotfiles']

    - import_tasks: tasks/homebrew.yml
      when: configure_homebrew
      tags: ['homebrew']

    - import_tasks: tasks/mas.yml
      when: configure_macstore
      tags: ['mas']

    - import_tasks: tasks/sudoers.yml
      when: configure_sudoers
      tags: ['sudoers']

    - import_tasks: tasks/osx.yml
      when: configure_osx
      tags: ['osx']

    - import_tasks: tasks/dock.yml
      when: configure_dock
      tags: ['dock']

    - import_tasks: tasks/terminal.yml
      when: configure_terminal
      tags: ['terminal']

    - import_tasks: tasks/extra-packages.yml
      tags: ['extra-packages']
    
    - import_tasks: tasks/yubikey.yml
      when: configure_yubikey
      tags: ['yubikey']

    - import_tasks: tasks/vscode.yml
      when: configure_vsc
      tags: ['visual-studio-code']

    - import_tasks: tasks/rclone.yml
      when: configure_rclone
      tags: ['rclone']

    - name: Run configured post-provision ansible task files.
      include_tasks: "{{ outer_item }}"
      loop_control:
        loop_var: outer_item
      with_fileglob: "{{ post_provision_tasks|default(omit) }}"
      tags: ['post']

  handlers:
    # handler for homebrew
    - name: Clear homebrew cache
      file:
        path: "{{ homebrew_cache_path.stdout | trim }}"
        state: absent
      when: 'homebrew_clear_cache | bool'
      become: "{{ (homebrew_user != ansible_user_id) | bool }}"
      become_user: "{{ homebrew_user }}"

    # rclone handler
    - name: Update facts
      action: setup
