---
- name: Install dockutil.
  homebrew:
    name: dockutil
    state: present

- name: Remove configured Dock items.
  include_tasks: dock-remove.yml
  loop: "{{ dockitems_remove }}"

- name: Ensure required dock items exist.
  include_tasks: dock-add.yml
  loop: "{{ dockitems_persist }}"

- name: Ensure dock items are in correct position.
  include_tasks: dock-position.yml
  when:
    - item.pos is defined
    - item.pos > 0
  loop: "{{ dockitems_persist }}"
