---
# Add Homebrew ZSH to allowed shells
#- name: Ensure ZSH is installed.
#  homebrew: name=zsh state=present

- name: Get the path to ZSH
  become: false
  local_action: command which zsh
  register: zsh_path

- name: "Ensure homebrew zsh is in allowed shells"
  lineinfile:
    path: /etc/shells
    line: "{{ zsh_path.stdout }}"
  become: false

# Add Homebrew BASH to allowed shells
#- name: Ensure BASH is installed.
#  homebrew: name=bash state=present

- name: Get the path to BASH
  become: false
  local_action: command which bash
  register: bash_path

- name: "Ensure homebrew bash is in allowed shells"
  lineinfile:
    path: /etc/shells
    line: "{{ bash_path.stdout }}"
  become: false

# Set default shell  
- name: Set ZSH as the default shell
  shell: chsh -s $(which zsh) {{ lookup('env', 'USER') }}
  when: set_zsh
  become: false

- name: Set BASH as the default shell
  shell: chsh -s $(which bash) {{ lookup('env', 'USER') }}
  when: set_bash 
  become: false

# Use sudo once .macos-defaults can be run via root with no user interaction.
- name: Run .macos-defaults dotfiles.
  shell: "sh {{ osx_script }}"
# command: "{{ osx_script }}"
  changed_when: false
  become: true
