---
# Synthwave Terminal theme.
- name: Get current Terminal profile.
  command: defaults read com.apple.terminal 'Default Window Settings'
  register: terminal_theme
  changed_when: false
  check_mode: false

- name: Ensure custom Terminal profile is added.
  copy:
    src: files/terminal/synthwave.terminal
    dest: /tmp/synthwave.terminal
  changed_when: false
  when: "'synthwave' not in terminal_theme.stdout"

- name: Ensure custom Terminal profile is added.
  command: open /tmp/synthwave.terminal
  changed_when: false
  when: "'synthwave' not in terminal_theme.stdout"

- name: Ensure custom Terminal profile is set as default.
  command: "{{ item }}"
  with_items:
    - defaults write com.apple.terminal 'Default Window Settings' -string synthwave
    - defaults write com.apple.terminal 'Startup Window Settings' -string synthwave
  changed_when: false
  when: "'synthwave' not in terminal_theme.stdout"

- name: create Terminal Themes directory
  file: 
    path: "~/projects/Terminal-Color-Schemes"
    state: directory

- name: clone Terminal Themes to project directory
  git:
    repo: https://github.com/ei9h7/Terminal-Color-Schemes
    dest: "{{ lookup('env', 'HOME') }}/projects/Terminal-Color-Schemes"
    accept_hostkey: yes
    recursive: yes
