---
# Linux Yubikey Configuration

# Install required apt packages
- name: Install yubi dependencies
  become: true
  apt:
    pkg: "{{ yubi_depends }}"
    state: latest
    install_recommends: no
    update_cache: "{{ apt_update_cache }}"
    cache_valid_time: "{{ apt_cache_time }}" 

# Remove gnome keyring fuckery
- name: gnome keyring fuckery
  become: true
  apt:
    pkg: libpam-gnome-keyring
    state: absent
    
# Ensure yubikey udev rule exists      
- name: Ensure udev rule is present
  become: true
  file:
    path: "/etc/udev/rules.d/99-yubikeys.rules"
    state: touch

- name: Ensure udev rule is correct
  become: true
  lineinfile:
    path: "/etc/udev/rules.d/99-yubikeys.rules"
    line: 'ACTION=="add",SUBSYSTEM=="usb", ATTR{idVendor}=="1050", ATTR{idProduct}=="0404", OWNER="${USER}"'
