# taps
tap "homebrew/bundle"
tap "homebrew/core"
tap "homebrew/cask-fonts"

# formula
brew "cowsay"
brew "gcc"
cask "font-victor-mono-nerd-font"
cask "font-jetbrains-mono-nerd-font"
# brew "whalebrew"

# casks

# whalebrew
# whalebrew "3i9h7/docker-pyrit"
